### ISSUE TITLE
SIGSEGV in conjunction with Http/TLS

### ISSUE THREAD

**Issue by grocid** [murlokswarm/app#101]
It seems that calling the FilePicker in conjunction with the `http.Client` may sometimes cause a SIGSEGV. I have not found the cause of this problem, but here is a stack trace.

```[signal SIGSEGV: segmentation violation code=0x1 addr=0x4a1c50 pc=0x7fffd710805d]

runtime stack:
runtime.throw(0x43c764f, 0x2a)
	/usr/local/opt/go/libexec/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
	/usr/local/opt/go/libexec/src/runtime/signal_unix.go:351 +0x2b8

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x42fd5a0, 0xc42006be78, 0x40e609c)
	/usr/local/opt/go/libexec/src/runtime/cgocall.go:132 +0xe4 fp=0xc42006be48 sp=0xc42006be08 pc=0x4003fb4
github.com/murlokswarm/mac._Cfunc_Driver_Run()
	github.com/murlokswarm/mac/_obj/_cgo_gotypes.go:157 +0x41 fp=0xc42006be78 sp=0xc42006be48 pc=0x42e3461
github.com/murlokswarm/mac.(*Driver).Run(0xc420098ff0)
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/mac/driver.go:54 +0x29 fp=0xc42006be88 sp=0xc42006be78 pc=0x42e5db9
github.com/murlokswarm/app.Run()
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/app/app.go:49 +0x35 fp=0xc42006bea0 sp=0xc42006be88 pc=0x41cd505
main.main()
	/Users/carl/Utveckling/Go/src/pass/main.go:99 +0x1e9 fp=0xc42006bf80 sp=0xc42006bea0 pc=0x42fa159
runtime.main()
	/usr/local/opt/go/libexec/src/runtime/proc.go:185 +0x20d fp=0xc42006bfe0 sp=0xc42006bf80 pc=0x402dbcd
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42006bfe8 sp=0xc42006bfe0 pc=0x40595d1

goroutine 5 [syscall, locked to thread]:
github.com/murlokswarm/mac._Cfunc_Picker_NewFilePicker(0x5e1f710, 0x100)
	github.com/murlokswarm/mac/_obj/_cgo_gotypes.go:336 +0x45
github.com/murlokswarm/mac.newFilePicker(0xc420000100, 0xc420166010, 0x0)
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/mac/picker.go:38 +0x198
github.com/murlokswarm/mac.(*Driver).NewElement(0xc420098ff0, 0x43869e0, 0xc420166020, 0xc420166020, 0x4013418)
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/mac/driver.go:72 +0x231
github.com/murlokswarm/app.NewFilePicker(0x4000100, 0xc420166010, 0xc4222f3940, 0x4061aab)
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/app/picker.go:15 +0xa0
main.(*File).ReadFile(0xc4203b0070)
	/Users/carl/Utveckling/Go/src/pass/file.go:141 +0x6e
reflect.Value.call(0x438a060, 0xc4203b0070, 0x1613, 0x43b6ab4, 0x4, 0xc4222f3cd8, 0x0, 0x0, 0x43381c0, 0x5, ...)
	/usr/local/opt/go/libexec/src/reflect/value.go:434 +0x906
reflect.Value.Call(0x438a060, 0xc4203b0070, 0x1613, 0xc4222f3cd8, 0x0, 0x0, 0xc42000e008, 0x13, 0x5)
	/usr/local/opt/go/libexec/src/reflect/value.go:302 +0xa4
github.com/murlokswarm/markup.callComponentMethod(0x438a060, 0xc4203b0070, 0x1613, 0xc422224300, 0xfb, 0x438a060, 0xc4203b0070)
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/markup/handler.go:61 +0x3b3
github.com/murlokswarm/markup.HandleEvent(0xe811740889ae153f, 0x39789a14aafc6aa6, 0xc4201760b8, 0x8, 0xc422224300, 0xfb)
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/markup/handler.go:33 +0x140
github.com/murlokswarm/app.HandleEvent(0xc4202b4000, 0x16d)
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/app/js.go:186 +0x12e
github.com/murlokswarm/mac.onJSCall.func1()
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/mac/js.go:14 +0x33
github.com/murlokswarm/app.startUIGoroutine()
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/app/ui.go:110 +0x47
created by github.com/murlokswarm/app.init.0
	/Users/carl/Utveckling/Go/src/github.com/murlokswarm/app/ui.go:103 +0xa0

goroutine 125 [IO wait]:
internal/poll.runtime_pollWait(0x479ff70, 0x72, 0x0)
	/usr/local/opt/go/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42013a218, 0x72, 0xffffffffffffff00, 0x457c680, 0x45789f0)
	/usr/local/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42013a218, 0xc420204000, 0x1000, 0x1000)
	/usr/local/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42013a200, 0xc420204000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc42013a200, 0xc420204000, 0x1000, 0x1000, 0xc42013908b, 0xc420085180, 0x473b6c8)
	/usr/local/opt/go/libexec/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42017c048, 0xc420204000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc42015eba0, 0x5f083b0, 0xc42017c048, 0x5, 0xc42017c048, 0xc42224f9e0)
	/usr/local/opt/go/libexec/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc420084e00, 0x43d3a17, 0xc420084f20, 0x402e1bb)
	/usr/local/opt/go/libexec/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc420084e00, 0xc420139000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/crypto/tls/conn.go:1134 +0x110
net/http.(*persistConn).Read(0xc420160000, 0xc420139000, 0x1000, 0x1000, 0xc42017e940, 0xc42019c058, 0x4053d30)
	/usr/local/opt/go/libexec/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc4200e88a0)
	/usr/local/opt/go/libexec/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc4200e88a0, 0x1, 0x0, 0x0, 0x0, 0xc4200928a0, 0x0)
	/usr/local/opt/go/libexec/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc420160000)
	/usr/local/opt/go/libexec/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/opt/go/libexec/src/net/http/transport.go:1186 +0xa2e

goroutine 126 [select]:
net/http.(*persistConn).writeLoop(0xc420160000)
	/usr/local/opt/go/libexec/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/opt/go/libexec/src/net/http/transport.go:1187 +0xa53```

**Comment by maxence-charriere** [comment]
Not sure about this.
I m pretty close to release the version 2 of this package and I reimplemented the file picker yesterday.
It should become more stable.

**Comment by grocid** [comment]
Will you add a `Save File` dialog as well?

**Comment by maxence-charriere** [comment]
I did not but we can put that on the loop.

**Comment by maxence-charriere** [comment]
Should be fix with v2, please reopen if there is still issue.
