### ISSUE TITLE
High Sierra Compatibility

### ISSUE THREAD

**Issue by FenwickElliott** [murlokswarm/app#77]
First let me say thank you, this is a great project and I am very grateful for all the time you must have put into it.

Should this project be runnable on High Sierra? I can run it in Sierra but it crashes when I run it on High Sierra. I know your readme only lists Sierra but I'm hoping there is a way to make this work.

Please let me know if there is anything I can do to help or if you need any more info about my system.

(My machine has a TouchBar incase that is relevant but I tried the fix that worked in the previous crash on run issue #15 `go build -ldflags -s`)

Thank you,

## System Info

<img width="581" alt="screen shot 2017-10-24 at 1 02 19 pm" src="https://user-images.githubusercontent.com/24613078/31957931-408d3d3a-b8be-11e7-8ead-316e0d554f5f.png">

## Go ENV
```
GOARCH="amd64"
GOBIN="/Users/charles/geeK/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/charles/geeK/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wz/gvlmt8yx7vx3gcs_7c7m6bg80000gn/T/go-build782246593=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

## To Replicate
```
pyrE:fenwickelliott charles$ git clone https://github.com/murlokswarm/examples.git
Cloning into 'examples'...
remote: Counting objects: 117, done.
remote: Total 117 (delta 0), reused 0 (delta 0), pack-reused 117
Receiving objects: 100% (117/117), 3.55 MiB | 1.20 MiB/s, done.
Resolving deltas: 100% (46/46), done.
pyrE:fenwickelliott charles$ cd examples/mac/hello
pyrE:hello charles$ go build
pyrE:hello charles$ ./hello
```

## Output
```
INFO  2017/10/24 13:16:48 driver.go:57: driver *mac.Driver is loaded
INFO  2017/10/24 13:16:48 component.go:62: main.Hello has been registered under the tag Hello
INFO  2017/10/24 13:16:48 component.go:62: main.AppMainMenu has been registered under the tag AppMainMenu
INFO  2017/10/24 13:16:48 component.go:62: main.WindowMenu has been registered under the tag WindowMenu
SIGTRAP: trace trap
PC=0x7fff3aad95af m=4 sigcode=1
signal arrived during cgo execution

goroutine 5 [syscall, locked to thread]:
runtime.cgocall(0x4193b30, 0xc42010bcb0, 0xc42010bcd8)
	/usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc42010bc80 sp=0xc42010bc40 pc=0x4004534
github.com/murlokswarm/mac._Cfunc_Window_CallJS(0x5f016f0, 0x4504b80)
	github.com/murlokswarm/mac/_obj/_cgo_gotypes.go:435 +0x41 fp=0xc42010bcb0 sp=0xc42010bc80 pc=0x4187fb1
github.com/murlokswarm/mac.(*window).Mount.func1(0x5f016f0, 0x4504b80)
	/Users/charles/geeK/go/src/github.com/murlokswarm/mac/window.go:124 +0x6a fp=0xc42010bce8 sp=0xc42010bcb0 pc=0x41908ba
github.com/murlokswarm/mac.(*window).Mount(0xc420140000, 0x43090c0, 0xc420010760)
	/Users/charles/geeK/go/src/github.com/murlokswarm/mac/window.go:124 +0x2f2 fp=0xc42010bdb0 sp=0xc42010bce8 pc=0x418e482
main.newMainWindow(0xc42000e038, 0x4309080)
	/Users/charles/geek/go/src/fenwickelliott/examples/mac/hello/main.go:52 +0xe6 fp=0xc42010bf60 sp=0xc42010bdb0 pc=0x4192a76
main.main.func1()
	/Users/charles/geek/go/src/fenwickelliott/examples/mac/hello/main.go:24 +0x8c fp=0xc42010bf98 sp=0xc42010bf60 pc=0x4192c9c
github.com/murlokswarm/mac.onLaunch.func1()
	/Users/charles/geeK/go/src/github.com/murlokswarm/mac/driver.go:120 +0x35 fp=0xc42010bfa8 sp=0xc42010bf98 pc=0x418fea5
github.com/murlokswarm/app.startUIGoroutine()
	/Users/charles/geeK/go/src/github.com/murlokswarm/app/ui.go:110 +0x47 fp=0xc42010bfe0 sp=0xc42010bfa8 pc=0x417f177
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42010bfe8 sp=0xc42010bfe0 pc=0x4058e21
created by github.com/murlokswarm/app.init.0
	/Users/charles/geeK/go/src/github.com/murlokswarm/app/ui.go:103 +0xa0

goroutine 1 [syscall, locked to thread]:
github.com/murlokswarm/mac._Cfunc_Driver_Run()
	github.com/murlokswarm/mac/_obj/_cgo_gotypes.go:157 +0x41
github.com/murlokswarm/mac.(*Driver).Run(0xc420080bd0)
	/Users/charles/geeK/go/src/github.com/murlokswarm/mac/driver.go:54 +0x29
github.com/murlokswarm/app.Run()
	/Users/charles/geeK/go/src/github.com/murlokswarm/app/app.go:49 +0x35
main.main()
	/Users/charles/geek/go/src/fenwickelliott/examples/mac/hello/main.go:35 +0x48

rax    0xd1b4000
rbx    0x70000247dd40
rcx    0x10000000000
rdx    0x103
rdi    0x12068
rsi    0x100
rbp    0x70000247dcf0
rsp    0x70000247dcc0
r8     0x4502bc0
r9     0x40
r10    0x4502bb8
r11    0xffffffffffffffff
r12    0x504a9b8
r13    0x70000247dda8
r14    0x70000247dd00
r15    0x504a9b8
rip    0x7fff3aad95af
rflags 0x246
cs     0x2b
fs     0x0
gs     0x0
```

**Comment by maxence-charriere** [comment]
Mmm look like the problem come from the cgo call to Window_CallJS.
I will take a look when I have a moment. Have to install High Sierra first.
Thanks for reporting this.

**Comment by malkomalko** [comment]
FYI, I get an error on 10.12.6 that's very similar with the exact same steps.  Maybe it's an Xcode 9 problem?

```
> ./hello
INFO  2017/10/28 08:26:14 driver.go:57: driver *mac.Driver is loaded
INFO  2017/10/28 08:26:14 component.go:62: main.Hello has been registered under the tag Hello
INFO  2017/10/28 08:26:14 component.go:62: main.AppMainMenu has been registered under the tag AppMainMenu
INFO  2017/10/28 08:26:14 component.go:62: main.WindowMenu has been registered under the tag WindowMenu
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fffe29f2b52]

runtime stack:
runtime.throw(0x420a0f4, 0x2a)
        /usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
        /usr/local/Cellar/go/1.9.1/libexec/src/runtime/signal_unix.go:351 +0x2b8

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4192ee0, 0xc420055f38, 0x4006924)
        /usr/local/Cellar/go/1.9.1/libexec/src/runtime/cgocall.go:132 +0xe4 fp=0xc420055f08 sp=0xc420055ec8 pc=0x4003be4
github.com/murlokswarm/mac._Cfunc_Driver_Run()
        github.com/murlokswarm/mac/_obj/_cgo_gotypes.go:157 +0x41 fp=0xc420055f38 sp=0xc420055f08 pc=0x4186b81
github.com/murlokswarm/mac.(*Driver).Run(0xc420082ae0)
        /Users/malkomalko/projects/go/src/github.com/murlokswarm/mac/driver.go:54 +0x29 fp=0xc420055f48 sp=0xc420055f38 pc=0x41894d9
github.com/murlokswarm/app.Run()
        /Users/malkomalko/projects/go/src/github.com/murlokswarm/app/app.go:49 +0x35 fp=0xc420055f60 sp=0xc420055f48 pc=0x417d1a5
main.main()
        /Users/malkomalko/projects/go/src/github.com/malkomalko/examples/murlokswarm-app/mac/hello/main.go:35 +0x48 fp=0xc420055f80 sp=0xc420055f60 pc=0x4191fe8
runtime.main()
        /usr/local/Cellar/go/1.9.1/libexec/src/runtime/proc.go:185 +0x20d fp=0xc420055fe0 sp=0xc420055f80 pc=0x402d46d
runtime.goexit()
        /usr/local/Cellar/go/1.9.1/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420055fe8 sp=0xc420055fe0 pc=0x40584d1

goroutine 19 [chan receive]:
github.com/murlokswarm/app.startUIGoroutine()
        /Users/malkomalko/projects/go/src/github.com/murlokswarm/app/ui.go:109 +0x5f
created by github.com/murlokswarm/app.init.0
        /Users/malkomalko/projects/go/src/github.com/murlokswarm/app/ui.go:103 +0xa0
```

**Comment by maxence-charriere** [comment]
Hey guys, just fixed the problem.
See https://github.com/murlokswarm/mac/pull/23

**Comment by maxence-charriere** [comment]
Not there is also the warning ```picker.m:32:17: warning: 'NSFileHandlingPanelOKButton' is deprecated: first deprecated in macOS 10.13 [-Wdeprecated-declarations]
/System/Library/Frameworks/AppKit.framework/Headers/NSSavePanel.h:21:5: note: 'NSFileHandlingPanelOKButton' has been explicitly marked deprecated here```
This warning will be fix with the v2 I m currently working on.
